# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.10.5
      - name: Install dependencies
        run: dart pub get
      - name: activate webdev
        run: dart pub global activate webdev
      - name: upgrade dependencies
        run: dart pub get
      - name: AngularDart Build
        run: dart pub global run webdev build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./app/build # The folder the action should deploy.
